# Generated by Django 5.1.6 on 2025-06-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
